name: synth_seg_py310
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow-gpu==2.11.0
#  - cudatoolkit=11.6.0 # Uncomment for MPCDF cluster
#  - cudnn=8.4.1 # Uncomment for MPCDF cluster
  - numpy=1.23.5
  - scikit-learn==1.2.1
  - nibabel=5.0.1
  - tqdm=4.65.0
  - ipython=8.11.0
  - Pillow=9.4.0
  - pandas=1.5.3
  - imageio=2.26.0
  - matplotlib==3.7.1 # Uncomment if we really need it
  - pip

#  - matplotlib==3.7.1 # Uncomment if we really need it
#  - h5py=2.10.0 # This is automatically installed. If we don't explicitly need it, we don't want it
#  - Keras=2.3.1 # Pretty sure we don't want that anymore
#  - Keras-Applications=1.0.8 # Pretty sure we don't want that anymore
#  - Keras-Preprocessing=1.1.2 # Pretty sure we don't want that anymore
