name: synth_seg_py38
channels:
  - conda-forge
dependencies:
  - python=3.8
  - h5py=2.10.0
  - imageio=2.22.4
  - Keras=2.3.1
  - Keras-Applications=1.0.8
  - Keras-Preprocessing=1.1.2
  - matplotlib=3.2.1
  - nibabel=4.0.2
  - numpy=1.18.5
  - pandas=1.0.3
  - Pillow=9.3.0
  - scikit-learn=0.22.2.post1
  - tensorflow-gpu=2.2.0
  - tqdm=4.64
  - ipython=8.7.0
  - wandb==0.14.0
