name: synth_seg_py39
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - tensorflow==2.11.0
  - numpy=1.24.2
  - scikit-learn==1.2.2
  - nibabel=5.0.1
  - tqdm=4.65.0
  - ipython=8.11.0
  - Pillow=9.4.0
  - pandas=1.5.3
  - imageio=2.26.0
  - matplotlib==3.7.1
