name: Build and Push Docker Image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: nrdg
        password: ${{secrets.CR_PAT_NRDG}}

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build and push docker image
      run: sh ./docker-build.sh \
        "${{github.sha}}" \
        "nrdg"

    - name: Build and push a tagged image
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        sh ./docker/docker-build.sh "${{ github.event.release.tag_name }}" "nrdg"
